# Generated by Django 5.0.3 on 2024-05-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_remove_chatroom_is_public_chatroom_admins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinroom',
            name='approved_at',
        ),
        migrations.AlterField(
            model_name='joinroom',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
