# Generated by Django 5.0.3 on 2024-05-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_remove_joinroom_approved_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created',
        ),
    ]
